---
title: "topic hierarchy"
output: html_notebook
---
sort out directory for relative filepaths
```{r}
getwd()
#install.packages("rCharts")
library(networkD3)
library(devtools)
#install_github('rCharts', 'ramnathv')
library(rCharts)

```
read in data which was prepared in python
```{r}

sankey_data <- read.csv("./sankey_data.csv", header = TRUE)
sankey_data$source2 <- paste0("topic", sankey_data$source)
sankey_data$target2 <- paste0("topic_", sankey_data$target)
nodes_df <- data.frame(ID = unique(c(sankey_data$source2, sankey_data$target2)))
class(nodes_df)
```

Exploring plots of relationships between topics

```{r}

sankeyNetwork(Links = sankey_data, Nodes = nodes_df, Source = "source2",
             Target = "target2", Value = "value", fontSize = 12, NodeID = "ID", nodeWidth = 30)
```
try rCharts instead:
```{r}

edgelist <- data.frame(matrix(ncol = 3, nrow = 85))
colnames(edgelist) <-  c("source", "target", "value")
#make character rather than numeric for proper functioning
edgelist$source <- as.character(sankey_data$source)
edgelist$target <- as.character(sankey_data$target)
sankeyPlot <- rCharts$new()
sankeyPlot$setLib('libraries/widgets/d3_sankey')
sankeyPlot$setTemplate(script = "libraries/widgets/d3_sankey/layouts/chart.html")
sankeyPlot$set(
  data = edgelist,
  nodeWidth = 15,
  nodePadding = 10,
  layout = 32,
  width = 960,
  height = 500
)
sankeyPlot$print(chartId = 'sankey1')
```

```{r}

sankeyPlot <- rCharts$new()
sankeyPlot$setLib('http://timelyportfolio.github.io/rCharts_d3_sankey')


#Following @timelyportfolio, we configure the chart and then open it to a browser window:

sankeyPlot$set(
  data = sankey_data,
  nodeWidth = 15,
  nodePadding = 10,
  layout = 32,
  width = 400,
  height = 200
)

sankeyPlot
```

